Add multiple namespace support
openfaas/faas-idler pull request #42
Opened 2020-08-31 11:20 UTC by viveksyngh

## Description

## How Has This Been Tested?

## Checklist:

I have:

- [ ] updated the documentation if required
- [ ] read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] signed-off my commits with `git commit -s`
- [ ] added unit tests

2020-09-21 12:55 UTC, goggi commented
Great work! Any ETA on the release for the fix?

2020-09-21 13:15 UTC, alexellis commented
This is already on the public roadmap, but there is no ETA for the open-source features.

Note that we do prioritise the roadmap and feature requests for [Premium Subscription clients](https://www.openfaas.com/support), if that's of interest, then take a look?

2020-09-21 13:15 UTC, alexellis commented
(@viveksyngh, out of interest, are any changes required for this PR?)

2020-10-21 21:21 UTC, alexellis commented on main.go
> +		querySt := url.QueryEscape(`sum(rate(gateway_function_invocation_total{function_name="` + functionName + `", code=~".*"}[` + duration + `])) by (code, function_name)`)
This shouldn't have changed as part of the PR? Can you explain the change?

2020-10-21 21:22 UTC, alexellis requested changes
I noticed a change that I wasn't expecting

2020-10-26 16:21 UTC, viveksyngh commented on main.go
> +		querySt := url.QueryEscape(`sum(rate(gateway_function_invocation_total{function_name="` + functionName + `", code=~".*"}[` + duration + `])) by (code, function_name)`)
I have removed that changes .. it go introduced while, I was testing a different PR.

2020-10-28 17:00 UTC, viveksyngh commented
I have removed the unexpected change.

2020-11-16 10:19 UTC, alexellis approved these changes
Approved

2020-11-16 10:19 UTC, merged